/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContentRow: typeof import('./src/components/ContentRow.vue')['default']
    CopyRight: typeof import('./src/components/CopyRight.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MainRow: typeof import('./src/components/MainRow.vue')['default']
    TitleMaquee: typeof import('./src/components/TitleMaquee.vue')['default']
    TitleRow: typeof import('./src/components/TitleRow.vue')['default']
  }
}
